"""Builds a self-contained dashboard.html from Joe's logs + live account.

Single file, no CDN/network needed: inline CSS, vanilla JS, inline-SVG equity
curve. Data is injected as a JSON blob. Regenerated by `scripts/build_dashboard.py`
and at the end of the daily digest run.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone

from . import logbook as log
from .config import ROOT, RISK


def _read_jsonl(path) -> list[dict]:
    out = []
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    return out


def _gather() -> dict:
    equity_log = _read_jsonl(log.EQUITY)
    trades = _read_jsonl(log.TRADES)
    decisions = _read_jsonl(log.DECISIONS)

    # Live account/positions; fall back to last logged values if broker is down.
    account, positions = None, []
    alpaca_fills = {}  # symbol -> [(side, qty, price, ts), ...]
    try:
        from .broker import Broker
        from alpaca.trading.requests import GetOrdersRequest
        from alpaca.trading.enums import QueryOrderStatus

        b = Broker()
        account = b.account()
        positions = b.positions()

        # Fetch closed orders to get fill prices
        try:
            orders = b.trading.get_orders(
                GetOrdersRequest(status=QueryOrderStatus.CLOSED, limit=500)
            )
            for o in orders:
                if o.symbol not in alpaca_fills:
                    alpaca_fills[o.symbol] = []
                if float(o.filled_qty or 0) > 0:
                    alpaca_fills[o.symbol].append({
                        "side": str(o.side).split(".")[-1].lower(),
                        "qty": float(o.filled_qty),
                        "price": float(o.filled_avg_price) if o.filled_avg_price else None,
                        "ts": o.filled_at.isoformat() if o.filled_at else "",
                    })
        except Exception as exc:
            log.info(f"dashboard: alpaca fills unavailable ({exc!r})")
    except Exception as exc:
        log.info(f"dashboard: broker unavailable, using logs ({exc!r})")

    start = RISK.starting_equity
    if account:
        equity = account["equity"]
        cash = account["cash"]
        last_equity = account["last_equity"] or equity
    elif equity_log:
        equity = equity_log[-1].get("equity", start)
        cash = equity_log[-1].get("cash", 0.0)
        last_equity = equity
    else:
        equity, cash, last_equity = start, start, start

    # Equity curve: baseline + every logged snapshot (capped to the last 500).
    curve = [{"t": "start", "v": start}]
    for e in equity_log[-500:]:
        curve.append({"t": e.get("ts", ""), "v": e.get("equity", start)})
    if account:
        curve.append({"t": datetime.now(timezone.utc).isoformat(), "v": equity})

    winners = sum(1 for p in positions if p["unrealized_plpc"] > 0)
    win_rate = (winners / len(positions)) if positions else None

    # Enrich trades with Alpaca fill data: add buy/sell prices and realized P&L
    enriched_trades = []
    for t in reversed(trades):
        if t.get("status") == "error":
            continue
        t_out = t.copy()
        symbol = t.get("symbol", "")
        fills = alpaca_fills.get(symbol, [])

        # Match this trade to a fill by symbol + side + time proximity
        if fills:
            side = t.get("side", "").lower()
            # Find the closest fill in time
            closest = None
            closest_diff = float("inf")
            for fill in fills:
                if fill["side"] == side:
                    ts_str = t.get("ts", "")
                    if ts_str and fill["ts"]:
                        try:
                            t_dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
                            f_dt = datetime.fromisoformat(fill["ts"].replace("Z", "+00:00"))
                            diff = abs((t_dt - f_dt).total_seconds())
                            if diff < closest_diff:
                                closest_diff = diff
                                closest = fill
                        except ValueError:
                            pass
            if closest and closest_diff < 3600:  # within 1 hour
                t_out["fill_price"] = closest["price"]
                t_out["fill_qty"] = closest["qty"]

        enriched_trades.append(t_out)

    # Pair up buy/sell trades to calculate realized P&L
    paired = {}  # symbol -> {"buy": [...], "sell": [...]}
    for t in enriched_trades:
        sym = t.get("symbol", "")
        if sym not in paired:
            paired[sym] = {"buy": [], "sell": []}
        side = t.get("side", "").lower()
        if side in ["buy", "sell"]:
            paired[sym][side].append(t)

    # Calculate realized P&L for closed pairs
    for t in enriched_trades:
        sym = t.get("symbol", "")
        side = t.get("side", "").lower()
        if side == "sell" and "fill_price" in t and sym in paired:
            # Look for matching buy before this sell
            buys = [b for b in paired[sym]["buy"] if b.get("ts", "") < t.get("ts", "")]
            if buys:
                buy = buys[-1]  # most recent buy before sell
                if "fill_price" in buy:
                    qty = min(t.get("fill_qty", 0), buy.get("fill_qty", 0))
                    t["realized_pl"] = (t["fill_price"] - buy["fill_price"]) * qty
                    t["matched_buy_ts"] = buy.get("ts", "")

    return {
        "generated": datetime.now(timezone.utc).isoformat(),
        "start_equity": start,
        "equity": equity,
        "cash": cash,
        "day_pl": equity - last_equity,
        "day_pct": ((equity - last_equity) / last_equity) if last_equity else 0.0,
        "total_pl": equity - start,
        "total_pct": (equity - start) / start,
        "open_count": len(positions),
        "win_rate": win_rate,
        "winners": winners,
        "positions": [
            {
                "symbol": p["symbol"], "qty": p["qty"],
                "avg_entry": p["avg_entry"], "current_price": p["current_price"],
                "market_value": p["market_value"], "plpc": p["unrealized_plpc"] * 100,
                "pl": p["unrealized_pl"],
            } for p in positions
        ],
        "curve": curve,
        "trades": enriched_trades[:25],
        "decisions": list(reversed(decisions))[:30],
    }


def build_dashboard() -> str:
    data = _gather()
    html = _TEMPLATE.replace("/*__DATA__*/null", json.dumps(data, default=str))
    out = ROOT / "dashboard.html"
    out.write_text(html, encoding="utf-8")
    log.info(f"Dashboard written: {out}")
    return str(out)


_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<title>Joe · Trading Dashboard</title>
<style>
  :root{
    --bg:#020617; --panel:#0b1220; --panel2:#111c30; --line:#1e293b;
    --text:#f8fafc; --muted:#94a3b8; --pos:#22c55e; --neg:#f43f5e;
    --accent:#38bdf8;
    --mono:ui-monospace,"SF Mono","Cascadia Code","Fira Code",Consolas,monospace;
    --sans:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",sans-serif;
  }
  *{box-sizing:border-box}
  body{margin:0;background:
      radial-gradient(1200px 600px at 80% -10%,rgba(56,189,248,.08),transparent),
      var(--bg);color:var(--text);font-family:var(--sans);
      -webkit-font-smoothing:antialiased;line-height:1.5}
  .wrap{max-width:1200px;margin:0 auto;padding:32px 20px 64px}
  header{display:flex;align-items:flex-end;justify-content:space-between;
      gap:16px;flex-wrap:wrap;margin-bottom:28px}
  .brand{display:flex;align-items:center;gap:14px}
  .mark{font-size:38px;line-height:1;filter:drop-shadow(0 0 14px rgba(56,189,248,.35))}
  h1{font-family:var(--mono);font-size:30px;margin:0;letter-spacing:-.5px;
      text-shadow:0 0 18px rgba(248,250,252,.12)}
  .sub{color:var(--muted);font-size:13px;margin-top:2px}
  .updated{color:var(--muted);font-size:12px;font-family:var(--mono);text-align:right}
  .grid{display:grid;gap:14px;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));
      margin-bottom:22px}
  .card{background:linear-gradient(180deg,var(--panel2),var(--panel));
      border:1px solid var(--line);border-radius:14px;padding:16px 18px}
  .kpi .label{color:var(--muted);font-size:11px;text-transform:uppercase;
      letter-spacing:.08em;margin-bottom:8px}
  .kpi .value{font-family:var(--mono);font-size:24px;font-weight:600}
  .kpi .delta{font-family:var(--mono);font-size:13px;margin-top:4px}
  .pos{color:var(--pos)} .neg{color:var(--neg)} .muted{color:var(--muted)}
  .panel{background:linear-gradient(180deg,var(--panel2),var(--panel));
      border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:22px}
  .panel h2{font-family:var(--mono);font-size:14px;font-weight:600;margin:0 0 14px;
      color:var(--muted);text-transform:uppercase;letter-spacing:.08em}
  table{width:100%;border-collapse:collapse;font-size:13px}
  th{text-align:left;color:var(--muted);font-weight:500;font-size:11px;
      text-transform:uppercase;letter-spacing:.06em;padding:8px 10px;
      border-bottom:1px solid var(--line)}
  td{padding:10px;border-bottom:1px solid rgba(30,41,59,.5);font-family:var(--mono)}
  tr:last-child td{border-bottom:none}
  .num{text-align:right}
  .badge{display:inline-block;font-family:var(--mono);font-size:11px;font-weight:600;
      padding:2px 8px;border-radius:6px}
  .badge.buy{background:rgba(34,197,94,.14);color:var(--pos)}
  .badge.sell{background:rgba(244,63,94,.14);color:var(--neg)}
  .badge.hold{background:rgba(148,163,184,.14);color:var(--muted)}
  .feed{display:flex;flex-direction:column;gap:0}
  .item{display:grid;grid-template-columns:84px 1fr;gap:14px;padding:12px 0;
      border-bottom:1px solid rgba(30,41,59,.5)}
  .item:last-child{border-bottom:none}
  .item .sym{font-family:var(--mono);font-weight:600}
  .item .rsn{color:var(--muted);font-size:13px}
  .item .meta{font-family:var(--mono);font-size:11px;color:var(--muted);margin-top:3px}
  .empty{color:var(--muted);font-size:13px;padding:8px 2px}
  .chartwrap{position:relative;width:100%}
  svg{width:100%;height:auto;display:block}
  .axis{fill:var(--muted);font-family:var(--mono);font-size:11px}
  @media(max-width:560px){.kpi .value{font-size:20px}h1{font-size:24px}}
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="brand">
      <div class="mark">&#129433;</div>
      <div>
        <h1>Joe</h1>
        <div class="sub">Autonomous Swing Trader &middot; Paper Account</div>
      </div>
    </div>
    <div style="display:flex;flex-direction:column;align-items:flex-end;gap:6px">
      <div class="updated" id="updated"></div>
      <a href="about.html" style="font-family:var(--mono);font-size:11px;color:var(--accent);
          text-decoration:none;border:1px solid rgba(56,189,248,.25);border-radius:6px;
          padding:3px 10px;">About Joe</a>
    </div>
  </header>

  <div class="grid" id="kpis"></div>

  <div class="panel">
    <h2>Equity Curve</h2>
    <div class="chartwrap" id="chart"></div>
  </div>

  <div class="panel">
    <h2>Open Positions</h2>
    <div id="positions"></div>
  </div>

  <div class="panel">
    <h2>Recent Trades</h2>
    <div id="trades"></div>
  </div>

  <div class="panel">
    <h2>Joe's Decision Feed</h2>
    <div class="sub" style="margin:-6px 0 14px">Joe's reasoning each cycle — a BUY here is intent, not a guarantee it executed (risk limits, PDT, or cash can block it). Executed orders appear in <em>Recent Trades</em> above.</div>
    <div class="feed" id="decisions"></div>
  </div>
</div>

<script>
const D = /*__DATA__*/null;

const usd = n => (n<0?'-':'')+'$'+Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const pct = n => (n>=0?'+':'')+n.toFixed(2)+'%';
const sign = n => n>=0?'pos':'neg';
const esc = s => (s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const shortTime = ts => { const d=new Date(ts); return isNaN(d)?'':d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); };

// ---- updated stamp ----
document.getElementById('updated').textContent = 'Updated ' + shortTime(D.generated);

// ---- KPIs ----
const kpis = [
  {label:'Total Return', value:usd(D.total_pl), delta:pct(D.total_pct*100), cls:sign(D.total_pl)},
  {label:'Equity', value:usd(D.equity), delta:'from '+usd(D.start_equity), cls:'muted'},
  {label:"Day P&L", value:usd(D.day_pl), delta:pct(D.day_pct*100), cls:sign(D.day_pl)},
  {label:'Cash', value:usd(D.cash), delta:(D.open_count+' positions'), cls:'muted'},
  {label:'Open Positions', value:String(D.open_count), delta:(D.winners+' in profit'), cls:'muted'},
  {label:'Win Rate', value:(D.win_rate==null?'—':(D.win_rate*100).toFixed(0)+'%'), delta:'open positions green', cls:'muted'},
];
document.getElementById('kpis').innerHTML = kpis.map(k=>`
  <div class="card kpi">
    <div class="label">${k.label}</div>
    <div class="value ${k.cls}">${k.value}</div>
    <div class="delta ${k.cls}">${k.delta}</div>
  </div>`).join('');

// ---- Equity curve (inline SVG, Catmull-Rom smoothing) ----
function drawChart(){
  const W=1000,H=300,padL=8,padR=8,padT=18,padB=26;
  let pts = D.curve.map(p=>p.v);
  if(pts.length<2) pts = pts.length? [pts[0],pts[0]] : [D.start_equity,D.start_equity];
  const base = D.start_equity;
  let lo=Math.min(base,...pts), hi=Math.max(base,...pts);
  if(hi===lo){hi=lo+1;lo=lo-1;}
  const pad=(hi-lo)*0.12; lo-=pad; hi+=pad;
  const x=i=>padL+(i/(pts.length-1))*(W-padL-padR);
  const y=v=>padT+(1-(v-lo)/(hi-lo))*(H-padT-padB);
  const coords=pts.map((v,i)=>({x:x(i),y:y(v)}));
  // smooth path
  let d='M'+coords[0].x.toFixed(1)+','+coords[0].y.toFixed(1);
  for(let i=0;i<coords.length-1;i++){
    const p0=coords[i-1]||coords[i],p1=coords[i],p2=coords[i+1],p3=coords[i+2]||p2;
    const c1x=p1.x+(p2.x-p0.x)/6,c1y=p1.y+(p2.y-p0.y)/6;
    const c2x=p2.x-(p3.x-p1.x)/6,c2y=p2.y-(p3.y-p1.y)/6;
    d+=`C${c1x.toFixed(1)},${c1y.toFixed(1)} ${c2x.toFixed(1)},${c2y.toFixed(1)} ${p2.x.toFixed(1)},${p2.y.toFixed(1)}`;
  }
  const area=d+` L${coords[coords.length-1].x.toFixed(1)},${(H-padB)} L${coords[0].x.toFixed(1)},${(H-padB)} Z`;
  const up = pts[pts.length-1] >= base;
  const stroke = up? 'var(--pos)':'var(--neg)';
  const baseY=y(base).toFixed(1);
  document.getElementById('chart').innerHTML=`
  <svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="Equity curve">
    <defs>
      <linearGradient id="fill" x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stop-color="${up?'#22c55e':'#f43f5e'}" stop-opacity="0.28"/>
        <stop offset="100%" stop-color="${up?'#22c55e':'#f43f5e'}" stop-opacity="0"/>
      </linearGradient>
    </defs>
    <line x1="0" y1="${baseY}" x2="${W}" y2="${baseY}" stroke="var(--line)" stroke-width="1" stroke-dasharray="4 5"/>
    <text class="axis" x="6" y="${(+baseY-6)}">baseline ${usd(base)}</text>
    <path d="${area}" fill="url(#fill)"/>
    <path d="${d}" fill="none" stroke="${stroke}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
  </svg>`;
}
drawChart();

// ---- Positions ----
(function(){
  const el=document.getElementById('positions');
  if(!D.positions.length){el.innerHTML='<div class="empty">No open positions yet.</div>';return;}
  el.innerHTML=`<table><thead><tr>
    <th>Ticker</th><th class="num">Shares</th><th class="num">Avg Entry</th>
    <th class="num">Price</th><th class="num">Value</th><th class="num">P/L</th></tr></thead>
    <tbody>${D.positions.map(p=>`<tr>
      <td>${esc(p.symbol)}</td>
      <td class="num">${p.qty}</td>
      <td class="num">${usd(p.avg_entry)}</td>
      <td class="num">${usd(p.current_price)}</td>
      <td class="num">${usd(p.market_value)}</td>
      <td class="num ${sign(p.plpc)}">${usd(p.pl)} <span class="muted">${pct(p.plpc)}</span></td>
    </tr>`).join('')}</tbody></table>`;
})();

// ---- Trades ----
(function(){
  const el=document.getElementById('trades');
  if(!D.trades.length){el.innerHTML='<div class="empty">No trades yet.</div>';return;}
  el.innerHTML=`<table><thead><tr>
    <th>Time</th><th>Side</th><th>Ticker</th><th class="num">Qty</th><th class="num">Price</th><th class="num">P&L</th></tr></thead>
    <tbody>${D.trades.map(t=>{
      const side=(t.side||'').toLowerCase();
      const price=t.fill_price!=null?usd(t.fill_price):'—';
      const pl=t.realized_pl!=null?`<span class="${sign(t.realized_pl)}">${usd(t.realized_pl)}</span>`:'—';
      return `<tr>
        <td class="muted">${shortTime(t.ts)}</td>
        <td><span class="badge ${side}">${side.toUpperCase()}</span></td>
        <td>${esc(t.symbol)}</td>
        <td class="num">${t.fill_qty!=null?t.fill_qty:(t.qty!=null?t.qty:'—')}</td>
        <td class="num">${price}</td>
        <td class="num">${pl}</td>
      </tr>`;}).join('')}</tbody></table>`;
})();

// ---- Decision feed ----
(function(){
  const el=document.getElementById('decisions');
  if(!D.decisions.length){el.innerHTML='<div class="empty">No decisions logged yet.</div>';return;}
  el.innerHTML=D.decisions.map(d=>{
    const a=(d.action||'hold').toLowerCase();
    const conv=d.conviction!=null?(' &middot; conviction '+d.conviction+'/5'):'';
    return `<div class="item">
      <div><span class="badge ${a}">${a.toUpperCase()}</span></div>
      <div>
        <div class="sym">${esc(d.symbol)}</div>
        <div class="rsn">${esc(d.reasoning||'')}</div>
        <div class="meta">${shortTime(d.ts)}${conv}</div>
      </div>
    </div>`;}).join('');
})();
</script>
</body>
</html>"""
